name: Chrome headed
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://127.0.0.1:3000'
